== New Features in JDK 14
:sourcedir: ../src/main/java/net/bakaar/jdk/demo

=== Clear NullPointerException

* Add clearer message when chained method call

....
a.b.c.i = 99 => will throw this error if b is null :
-> Exception in thread "main" java.lang.NullPointerException:
   Cannot read field "c" because "a.b" is null at Prog.main(Prog.java:5)
....

Code Example :

[source,java,indent=0]
----
include::{sourcedir}/NullExample.java[tag=nullExample]
----

Will raise the following exception :

....
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "NullExample$A.getNumber()" because the return value of "NullExample$B.getA()" is null
	at NullExample.main(NullExample.java:8)
....

=== Records (preview)

see jdk 15

=== Pattern Matching instanceof (preview)

see jdk 15

=== Switch expression

* added in jdk 12
* `->` operator, no need of `break;` anymore
* can return a value
* if multiple statement then use `yield` keyword to return value
* if arrow operator is not use, `yield` keyword act as return (+ break)

Code example before :
[source,java,indent=0]
----
include::{sourcedir}/Switch.java[tag=switchBefore]
----

Code example with yield:
[source,java,indent=0]
----
include::{sourcedir}/Switch.java[tag=switchAfterYield]
----

Code example with `->` operator:
[source,java,indent=0]
----
include::{sourcedir}/Switch.java[tag=switchAfterArrow]
----

[.underline]#**Notes**#

* you cannot mix `yield` and the `->` operator
* if you need to write more than one statement per value, you have to use `yield`
